/*
 * This Java source file was generated by the Gradle 'init' task.
 */
// package eti_verma_sdet;

// import java.io.File;
// import java.io.IOException;
// import java.util.EnumSet;

// import org.openqa.selenium.Proxy;
// import org.openqa.selenium.WebDriver;
// import org.openqa.selenium.chrome.ChromeDriver;
// import org.openqa.selenium.remote.CapabilityType;
// import org.openqa.selenium.remote.DesiredCapabilities;
// //import org.testng.annotations.*;
// //import static org.testng.Assert.*;

// import io.github.bonigarcia.wdm.WebDriverManager;
// import net.lightbody.bmp.BrowserMobProxy;
// import net.lightbody.bmp.BrowserMobProxyServer;
// import net.lightbody.bmp.core.har.Har;
// import net.lightbody.bmp.proxy.CaptureType;

// public class App {
    
//     public void appHasAGreeting() throws InterruptedException, IOException {
    
//      BrowserMobProxy proxy1 = new BrowserMobProxyServer();
//         proxy1.start(4455);
//         Proxy seleProxy = new Proxy();
//         seleProxy.setHttpProxy("localHost" + proxy1.getPort());
//         seleProxy.setSslProxy("localHost" + proxy1.getPort());

//         DesiredCapabilities capabilities = new DesiredCapabilities();
//         capabilities.setCapability(CapabilityType.PROXY, seleProxy);
//         EnumSet<CaptureType> types = CaptureType.getAllContentCaptureTypes();
//         types.addAll(CaptureType.getCookieCaptureTypes());
//         types.addAll(CaptureType.getHeaderCaptureTypes());
//         types.addAll(CaptureType.getRequestCaptureTypes());
//         types.addAll(CaptureType.getResponseCaptureTypes());
        
//         proxy1.setHarCaptureTypes(types);
//         proxy1.newHar();

//         //start browser
//         WebDriverManager.chromedriver().setup();
//         WebDriver driver = new ChromeDriver();
//         driver.get("https://exactspace.co/");

//         driver.manage().window().maximize();
//         Thread.sleep(3000);

//         Har harFile = proxy1.getHar();
//         File file = new File(System.getProperty("user.dir")+ "/Eti_Verma_SDET///app//src//test//java//eti_verma_sdet");
//         harFile.writeTo(file);

//         System.out.println("Given all HAR file data");
//         driver.close();
//     }
// }


